# CHOOSE DEFAULT PORT AND HOST
DEFAULT_PORT = 12000
DEFAULT_HOST = "localhost"

# DEFAULT FILE FOLDERS
DEFAULT_STORAGE = './storage'
DEFAULT_SRC = '.'
DEFAULT_DST = './downloads'

# LOG FILE
DOWNLOAD_LOG_FILENAME = "download.log"
UPLOAD_LOG_FILENAME = "upload.log"
SERVER_LOG_FILENAME = "server.log"

MSG_SIZE = 1024

# TIMEOUTS (s)
TIMEOUT_RETRY_ATTEMPTS = 33
CLIENT_HANDSHAKE_TIMEOUT = 1
CLIENT_STOP_AND_WAIT_TIMEOUT = 0.03
SERVER_HANDSHAKE_TIMEOUT = 0.02
